{"name": "Авторизация с неверным логином", "status": "passed", "description": "Проверка, что система возвращает ошибку при неверном логине", "steps": [{"name": "Попытка авторизации с неверным логином: invalid_login, паролем: urnjdbtwut, именем: onmxnfsqiq", "status": "passed", "start": 1727644469542, "stop": 1727644469796}, {"name": "Проверка ошибки при неверном логине", "status": "passed", "start": 1727644469796, "stop": 1727644469796}], "start": 1727644469542, "stop": 1727644469796, "uuid": "9390020b-a0f6-462c-84a9-4b4042ab4c11", "historyId": "6c46507f6ed0591098d80724db9b31f4", "testCaseId": "6c46507f6ed0591098d80724db9b31f4", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_with_invalid_login", "labels": [{"name": "suite", "value": "Тесты логина курьера"}, {"name": "tag", "value": "@pytest.mark.usefixtures('courier_data')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-N041KP4"}, {"name": "thread", "value": "2608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}